icon.bident = auto|tantros-bident-ui
icon.archae = auto|tantros-team-archae-ui
icon.copper-bore = auto|tantros-copper-bore-ui
icon.copper-duct = auto|tantros-copper-duct-ui
icon.copper-duct-router = auto|tantros-copper-duct-router-ui
icon.silt-sifter = auto|tantros-silt-sifter-ui
icon.copper-bulkhead = auto|tantros-copper-bulkhead-ui
icon.copper-bulkhead-large = auto|tantros-copper-bulkhead-large-ui
icon.annealer = auto|tantros-annealer-ui
icon.arc-furnace = auto|tantros-arc-furnace-ui
icon.sealed-beam-node = auto|tantros-sealed-beam-node-ui
icon.tidal-turbine = auto|tantros-tidal-turbine-ui
icon.deep-sonar = auto|tantros-deep-sonar-ui